// Generated by https://quicktype.io

export interface PokeResponse {
  count: number;
  next: string;
  previous: null;
  results: PokemonSimpleDetail[];
}

export interface PokemonSimpleDetail {
  name: string;
  url: string;
}
